version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
